In [22]:
#svm support vector machine 
#it can be used in classification with more then 2 classes
#like a class blood group O+ A+ B+
#svm has a 2 support vector are divided in eqauly marging
#with support vector used to find out object is which class belong 
#1dimeension to 2 dimension and 2D to 3 dimantion easly converted
#svm as used kerneling for mathmatical computaion and find best accuracy
#kerneling are
#linear
#polynomial(poly)
#rbf(radical basis function)
#sigmoid

In [23]:
#import packages
import pandas as pd
import numpy as np
import pylab as pl
import scipy.optimize as opt #used mathmatical computusion
import matplotlib.pyplot as plt
%matplotlib inline

In [24]:
#access a dataset

df=pd.read_csv("cell_samples.csv")
df.head(6)



ID  Clump  UnifSize  UnifShape  MargAdh  SingEpiSize BareNuc  \
0  1000025      5         1          1        1            2       1   
1  1002945      5         4          4        5            7      10   
2  1015425      3         1          1        1            2       2   
3  1016277      6         8          8        1            3       4   
4  1017023      4         1          1        3            2       1   
5  1017122      8        10         10        8            7      10   

   BlandChrom  NormNucl  Mit  Class  
0           3         1    1      2  
1           3         2    1      2  
2           3         1    1      2  
3           3         7    1      2  
4           3         1    1      2  
5           9         7    1      4

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   ID           699 non-null    int64 
 1   Clump        699 non-null    int64 
 2   UnifSize     699 non-null    int64 
 3   UnifShape    699 non-null    int64 
 4   MargAdh      699 non-null    int64 
 5   SingEpiSize  699 non-null    int64 
 6   BareNuc      699 non-null    object
 7   BlandChrom   699 non-null    int64 
 8   NormNucl     699 non-null    int64 
 9   Mit          699 non-null    int64 
 10  Class        699 non-null    int64 
dtypes: int64(10), object(1)
memory usage: 60.2+ KB


In [26]:
df.columns

Index(['ID', 'Clump', 'UnifSize', 'UnifShape', 'MargAdh', 'SingEpiSize',
       'BareNuc', 'BlandChrom', 'NormNucl', 'Mit', 'Class'],
      dtype='object')

In [27]:
#for object to int conversion process

df=df[pd.to_numeric(df['BareNuc'],errors='coerce').notnull()]
df['BareNuc']=df['BareNuc'].astype('int64')

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 683 entries, 0 to 698
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           683 non-null    int64
 1   Clump        683 non-null    int64
 2   UnifSize     683 non-null    int64
 3   UnifShape    683 non-null    int64
 4   MargAdh      683 non-null    int64
 5   SingEpiSize  683 non-null    int64
 6   BareNuc      683 non-null    int64
 7   BlandChrom   683 non-null    int64
 8   NormNucl     683 non-null    int64
 9   Mit          683 non-null    int64
 10  Class        683 non-null    int64
dtypes: int64(11)
memory usage: 64.0 KB


In [29]:
x=np.asarray(df[['Clump','UnifSize','MargAdh','BareNuc','NormNucl','Mit']])
x[0:5]

array([[ 5,  1,  1,  1,  1,  1],
       [ 5,  4,  5, 10,  2,  1],
       [ 3,  1,  1,  2,  1,  1],
       [ 6,  8,  1,  4,  7,  1],
       [ 4,  1,  3,  1,  1,  1]], dtype=int64)

In [30]:
y=np.asarray(df[['Class']])
y[0:5]

array([[2],
       [2],
       [2],
       [2],
       [2]], dtype=int64)

In [31]:
#preprocessing

from sklearn import preprocessing
x=preprocessing.StandardScaler().fit(x).transform(x)
x[0:5]


array([[ 0.19790469, -0.70221201, -0.63936553, -0.69885309, -0.61292736,
        -0.34839971],
       [ 0.19790469,  0.27725185,  0.75803177,  1.77286724, -0.28510482,
        -0.34839971],
       [-0.51164337, -0.70221201, -0.63936553, -0.4242175 , -0.61292736,
        -0.34839971],
       [ 0.55267873,  1.58320366, -0.63936553,  0.12505369,  1.3540079 ,
        -0.34839971],
       [-0.15686934, -0.70221201,  0.05933312, -0.69885309, -0.61292736,
        -0.34839971]])

In [32]:
#train and test data
#it is important part to be get best accuracy and easy to implement ml model
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=3)

print("train",x_train.shape,y_train.shape)
print("test", x_test.shape,y_test.shape)

train (546, 6) (546, 1)
test (137, 6) (137, 1)


In [33]:
#modeling

from sklearn import svm

#liniear
clf=svm.SVC(kernel='linear')
clf.fit(x_train,y_train)
yhat=clf.predict(x_test)
yhat[0:5]

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 2, 2, 4, 4], dtype=int64)

In [34]:
#evalution
from sklearn.metrics import jaccard_similarity_score
print("jaccard score%.2f"%jaccard_similarity_score(yhat,y_test))

jaccard score0.96


C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:664: FutureWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  FutureWarning)


In [35]:
#f1_score find accuracy
from sklearn.metrics import f1_score
f1_score(yhat,y_test,average='weighted')

0.9562043795620438

In [36]:
#kernel=plynomial(ploy)

clf2=svm.SVC(kernel='poly')
clf2.fit(x_train,y_train)
yhat2=clf2.predict(x_test)


C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [37]:
yhat2[0:5]

array([2, 2, 2, 4, 4], dtype=int64)

In [38]:
#jaccard
from sklearn.metrics import jaccard_similarity_score
print("jaccard score%.2f" %jaccard_similarity_score(yhat2,y_test))

jaccard score0.94


C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:664: FutureWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  FutureWarning)


In [39]:
#f1_score

from sklearn.metrics import f1_score
f1_score(yhat2,y_test,average='weighted')

0.942088595373267

In [40]:
#kernel=rbf

clf3=svm.SVC(kernel='rbf')
clf3.fit(x_train,y_train)
yhat3=clf3.predict(x_test)
yhat3[0:5]

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 4, 2, 4, 4], dtype=int64)

In [41]:
#jaccard
from sklearn.metrics import jaccard_similarity_score

print("jaccard_score %.2f" %jaccard_similarity_score(yhat3,y_test))

jaccard_score 0.96


C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:664: FutureWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  FutureWarning)


In [42]:
#f1_score

from sklearn.metrics import f1_score
f1_score(yhat3,y_test,average='weighted')

0.9634680337875674

In [43]:
#last kernel=sigmoid 
clf4=svm.SVC(kernel='sigmoid')
clf4.fit(x_train,y_train)
yhat4=clf4.predict(x_test)
yhat4[0:5]

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 4, 2, 4, 4], dtype=int64)

In [44]:
#jaccard similarity
#evalution
from sklearn.metrics import jaccard_similarity_score
print("jaccard_similarity %.2f " % jaccard_similarity_score(yhat4,y_test))

jaccard_similarity 0.96 


C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:664: FutureWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  FutureWarning)


In [45]:
#@f1_score
from sklearn.metrics import f1_score
f1_score(yhat4,y_test ,average='weighted')

0.9562043795620438

In [46]:
clf3

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [47]:
from sklearn.metrics import log_loss
log_loss(y_test,yhat4)

19.664868083230573

In [48]:
from sklearn.metrics import classification_report
print(classification_report(yhat3,y_test))

              precision    recall  f1-score   support

           2       0.96      0.97      0.97        77
           4       0.97      0.95      0.96        60

    accuracy                           0.96       137
   macro avg       0.96      0.96      0.96       137
weighted avg       0.96      0.96      0.96       137



In [49]:
df.head(15)

ID  Clump  UnifSize  UnifShape  MargAdh  SingEpiSize  BareNuc  \
0   1000025      5         1          1        1            2        1   
1   1002945      5         4          4        5            7       10   
2   1015425      3         1          1        1            2        2   
3   1016277      6         8          8        1            3        4   
4   1017023      4         1          1        3            2        1   
5   1017122      8        10         10        8            7       10   
6   1018099      1         1          1        1            2       10   
7   1018561      2         1          2        1            2        1   
8   1033078      2         1          1        1            2        1   
9   1033078      4         2          1        1            2        1   
10  1035283      1         1          1        1            1        1   
11  1036172      2         1          1        1            2        1   
12  1041801      5         3          3        3            2        3   
13  1043999      1         1          1        1            2        3   
14  1044572      8         7          5       10            7        9   

    BlandChrom  NormNucl  Mit  Class  
0            3         1    1      2  
1            3         2    1      2  
2            3         1    1      2  
3            3         7    1      2  
4            3         1    1      2  
5            9         7    1      4  
6            3         1    1      2  
7            3         1    1      2  
8            1         1    5      2  
9            2         1    1      2  
10           3         1    1      2  
11           2         1    1      2  
12           4         4    1      4  
13           3         1    1      2  
14           5         5    4      4